### ISSUE TITLE
Precompiled Amp and War files of latest build

### ISSUE THREAD

**Issue by DBlamire** [Open-MBEE/mms-alfresco#119]
Are there any precompiled amp and war files from the latest build?
We are having issues due to the strict network security at OrbitalATK and are unable to connect from the server on their network when we run the configuration.
Even if the server is set to reach out to the internet, we have certificate issues that prevent the build of the mms. 
If we had a precompiled version, artifacts to deploy an instance, this would help greatly.

V/r,
David Blamire
David.Blamire@OrbitalATK.com

**Comment by HuiJun** [comment]
Hi David,

Precompiled amps are now located on our release pages.
