### ISSUE TITLE
ShareUtils is using alfresco settings for share settings

### ISSUE THREAD

**Issue by kozchris** [Open-MBEE/mms-alfresco#209]
In file: mms/mms-ent/repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/util/ShareUtils.java the initializeUrls() method is setting the share properties to the alfresco properties. 

You can see this in the initializeUrls() code snip here:

`if (SHARE_URL == null) {
            SysAdminParams adminParams = services.getSysAdminParams();
            // int repoPort = adminParams.getAlfrescoPort();
            int repoPort = 8080;
            int sharePort = repoPort;
            // String protocol = adminParams.getAlfrescoProtocol();
            String protocol = "http";
            String host = adminParams.getAlfrescoHost();

            REPO_URL = String.format("%s://%s:%s/alfresco", protocol, host, repoPort);
            SHARE_URL = String.format("%s://%s:%s/share", protocol, host, sharePort);` 

This prevents being able to run the share and the repo on different servers.

It appears that there are already methods available to get the share information needed within this file: repo-amp/src/main/java/gov/nasa/jpl/view_repo/webscripts/HostnameGet.java

**Comment by HuiJun** [comment]
Agreed, we'll put this on the list for 3.3.0

**Comment by HuiJun** [comment]
Fixed in d9951570fa4095084e0db66ed4d904746d8a602f
