### ISSUE TITLE
No smtp settings option in mms.properties (and associated code to dynamically set this)

### ISSUE THREAD

**Issue by borromeotlhs** [Open-MBEE/mms-alfresco#26]
I noticed this error when I tried to invite someone to be an admin of an alfresco site (as a backdoor means of getting to the external alfresco URL):
2017-05-10 15:37:46,362  INFO  [web.scripts.ImapServerStatus] [http-bio-8080-exec-14] Successfully retrieved IMAP server status from Alfresco: disabled
 2017-05-10 15:59:22,936  WARN  [security.person.PersonServiceImpl] [http-bio-8080-exec-17] PersonService.getPeopleFilteredByProperty() is being called to find people by {http://www.alfresco.org/model/content/1.0}email. Only PROP_FIRSTNAME, PROP_LASTNAME, PROP_USERNAME are now used in the search, so fewer nodes may be returned than expected of there are more than 100 users in total.
 2017-05-10 15:59:23,222  ERROR [action.executer.MailActionExecuter] [http-bio-8080-exec-17] Failed to send email to ********@********.*** : org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov; message exceptions (1) are:
Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov
 2017-05-10 15:59:38,787  WARN  [security.person.PersonServiceImpl] [http-bio-8080-exec-17] PersonService.getPeopleFilteredByProperty() is being called to find people by {http://www.alfresco.org/model/content/1.0}email. Only PROP_FIRSTNAME, PROP_LASTNAME, PROP_USERNAME are now used in the search, so fewer nodes may be returned than expected of there are more than 100 users in total.
 2017-05-10 15:59:38,868  ERROR [action.executer.MailActionExecuter] [http-bio-8080-exec-17] Failed to send email to tbor...@ford.com : org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov; message exceptions (1) are:
Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.jpl.nasa.gov, 25; timeout -1;
  nested exception is:
java.net.UnknownHostException: smtp.jpl.nasa.gov

This makes me realize that 'mms.properites.example' doesn't have a section for IMAP settings, and I can't find the page to alter settings from the admin-console.

**Comment by HuiJun** [comment]
Ah, the smtp settings are in the alfresco-global.properties. I will look into a configurable option in mms.properties, but for now, you'll have unzip the amp and replace the values in the alfresco-global.properties that we add in at build time. Usually, we have a shared properties file in TOMCAT_HOME/shared/classes/alfresco-global.properties, but if you're running from the maven run profile, you'll have to edit these in ./repo-amp/src/test/properties/local/alfresco-global.properties, iirc.

**Comment by borromeotlhs** [comment]
why does the mms.git project have the smtp settings in
alfresco-global.properties, but the EMS-Repo.git doesn't?

I was figuring that if I wanted to expose this, that I'd have to make a
pull request in EMS-Repo to parameter-ize the smtp setting there, then
create an entry into either the mms-ent's root level pom and/or the mms-ent
mms.properties.example file. . .

Really, I'm trying to find the code in EMS-Repo responsible for sending
emails, so that I can see how invitation emails are sent (and thus what
code pulls in smtp server settings).  From there, I was figuring I could
also figure out a way to make a modal for smtp settings using those
whatever rendering system you all are using (what is it, btw?)

**Comment by Enquier** [comment]
My guess is because they weren't stripped out in the mms 2 code dump. SMTP settings
for EMS 2 were also via alfresco explorer (I.e alfresco global properties). the
alfresco documentation has pretty extensive documentation on how to
configure smtp and how to send out email templates and such. Their forums
have a couple of tutorials on how to constrict invites/notifications etc.

**Comment by Enquier** [comment]
As for parameterizing the settings I have been using my deployment took (Salt) to handle the parameterization. If you are doing a larger deployment you might investigate a tool like Saltstack or Ansible to handle that configuration without editing the source code. Greg green posted a pretty good ansible example to the openmbee list a few weeks back that might help you get started

**Comment by borromeotlhs** [comment]
I would not mind using things like salt, however, I feel that salt usage should stick to stuffing parameters that are ingested into settings files, that themselves, expose the configurable portions of any app or service, no?

If you are saying that I could use salt stack or ansible to configure a setting that needs compilation anyway (I don't think you are), I'd rather fix the source code and expose the setting with a commit so that I _can_ do salt stack type node configuration.   However, as I generally don't find a need for multiple mms servers, I'd stick to docker or some other containerization method.

**Comment by Enquier** [comment]
In this case that is what is required. EMS repo relies on the alfresco configuration parameters for smtp and authentication. These are set in the alfresco global properties file. In general I've found it the best practice to:
 1 install/configure tomcat , then

2 explode the alfresco install  into tomcat home , then

3 install the EMS amps into alfresco.war/share.war and then explode them to tomcat-home/webapps 

4 explode and copy mmsapp into webapps/alfresco. 

Apart from the installed amps the durable alfresco installation (i.e. Everything not inside alfresco.war) is not touched by EMS and can be safely parameterized in salt or at least manually configured separately including the global properties file in tomcat/shared/classes and the authentication settings. 

It also allows you to maintain a static alfresco installation/configuration with no reconfiguration between EMS versions/improvements.

**Comment by HuiJun** [comment]
Closing this issue, as it's an alfresco related issue rather than an MMS one.

**Comment by borromeotlhs** [comment]
But I’m on the mms repo. . .  So where do I go to make sure this setting is
integrated into the mms all in one setup file, as I need it programatically
stubbed our to then configure it from mms conf files?
