### ISSUE TITLE
"Alfresco Share" link isn't working at /alfresco path

### ISSUE THREAD

**Issue by borromeotlhs** [Open-MBEE/mms-alfresco#27]
If you try to access the /alfresco path, you will see a page with a bunch of links.  The second and third links are "Alfresco share" and "Aflresco webDAV".  

I've notice that clicking on the share link fails to resolve, as the url has 'localhost' in it.  However, the webDAV link works fine.  I think that both should correctly resolve to the whatever IP address or url that webDAV is dynamically calculating.

**Comment by HuiJun** [comment]
Hi @borromeotlhs, the share link should be using whatever is set in alfresco-global.properties. Can you access https://HOSTNAME:8080/share?

**Comment by borromeotlhs** [comment]
yes.  I'm looking at that page and noticing that the URL for itself (share)
resolves to local host, while the WebDAV correctly resolves to its IP
address.

**Comment by HuiJun** [comment]
For reference, the hostname that is used to generate the links from the /alfresco page is within alfresco-global.properties. We use an nginx proxy to reroute requests for /share properly, but this setting should be set if you want all links working from that page.
