### ISSUE TITLE
MMS won't build as per instructions in README for tag 3.3.0 any longer

### ISSUE THREAD

**Issue by borromeotlhs** [Open-MBEE/mms-alfresco#322]
I get the following error when I attempt to build the mms project from source:
 ```
[ERROR] Failed to execute goal on project mms-amp: Could not resolve dependencies for project gov.nasa.jpl.mbee:mms-amp:amp:3.3.0: Could not find artifact org.springframework.social:spring-social-facebook:jar:1.0.0.RC1 in alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public) -> [Help 1]
```

Is this an issue arising from this code being dependent upon having access to artifactory via a JFrog account (which I don't have at Ford)?  Or does it result from the stripping process for builds and releases not running properly to fix the pom when this is distributed to github?

In any case, any help or explanation to help me get the install done would be appreciated.  I can't remember how or if I had to fix this issue, but I am fairly certain it could be a proxy issue.  I have set up the proxy from eclipse, but perhaps this is a proxy settings issue from maven?  It shouldn't be, as eclipse should manage that, right?

INFO:
I am at the latest approved release tag on source of 3.3.0.  3.3.4, I think, is coming, but I wanted to be able to build from source and ensure I am at parity with the binaries being released.

Thanks,
TJ

**Comment by borromeotlhs** [comment]
Turned on debugging and found a non-public dependency is now blocking my maven build.
```
[ERROR] Failed to execute goal on project mms-amp: Could not resolve dependencies for project gov.nasa.jpl.mbee:mms-amp:amp:3.3.0: Could not find artifact org.springframework.social:spring-social-facebook:jar:1.0.0.RC1 in alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public) -> [Help 1]
```

I am wondering if this was fixed in future versions, and if so, what is the fix?  I am stuck for legacy reasons bringing up the mms repo at tag: 3.3.0 .

Any help would be greatly appreciated.

Thanks,
TJ Borromeo

**Comment by HuiJun** [comment]
Hi TJ,

Unfortunately, the artifact was removed from the alfresco repository right after the 3.3.0 release. There is a fix for 3.4.0 which is being released today. If you need a fix immediately, go ahead and add this repository to repo-amp/pom.xml.
```
        <repository>
            <id>spring</id>
            <name>Spring Maven Repository</name>
            <url>http://repo.spring.io/plugins-release/</url>
        </repository>
```

**Comment by borromeotlhs** [comment]
Awesome. I signed off for the night and will try this tomorrow!  I'll be back on to see if this works.  Thanks @HuiJun !

I think that if I can build it after this fix, then I am super super super excited for v3.4.0 (that is the latest one coming, right?)  I saw something up for review, but wanted to build the last official tagged release and then that one before commenting either way.  Unfortunately, I got stuck and didn't help myself when I named the two proxies the same thing and didn't find it until running maven with -X (d'oh!)

**Comment by borromeotlhs** [comment]
It seems that I now get past that error, but then get the swagger-codegen-mathematics-client error.

I am going to just pull 3.4.0 already, and try building that.  If I'm going to bother building something from the perspective of a public newcomer, I'd rather just climb the mountain on the newest release to help you all debug issues you may not see having access to the enterprise and jfrog and all the private dev stuff.  Ironically, I think that the alfresco stuff built, but the failing portion is the mms-amp.  I guess I could shove the binary releases you all put out, but I also feel that that would be 'cheating' those who are trying to help develop. . . ;)

**Comment by HuiJun** [comment]
Hmm, swagger-codegen-mathmatica-client should already be available on jcenter, which means it should resolve correctly even in 3.3.0. In 3.4.0, we added swagger-codegen-matlab-client, which is now also available on jcenter, since last week. Let me know if you're still getting that error, and if so, go ahead and post the error here so that we can investigate it further. Thanks.

**Comment by borromeotlhs** [comment]
Will do.  I just have to finish bringing the rest of 3.4.0 up.  I am stuck going "through" it until I get this demoed.  But I will circle back around to do this.

Would it help if I mentioned I don't have an artifactory/jfrog account? :)  I don't know if this matters, but I was able to build from v3.3.0 before without one, and suspect that perhaps the public archive necessary to build this is gone. . .

**Comment by borromeotlhs** [comment]
Oh, BTW: I built v3.4.0 successfully :)  So you have outside confirmation ahead of the Thursday meeting that mms builds.  Working on ve now.  I assume that a v18.5sp4 version of MD and the associated mdk (don't know the version as I haven't looked back at the compatibility chart yet) will work for v3.4.0 of mms?  Is this correct?
