### ISSUE TITLE
org.alfresco.error.AlfrescoRuntimeException: 09050000 GetModelsDiff return status is 404 while running the Alfresco

### ISSUE THREAD

**Issue by SripriyaAkondi** [Open-MBEE/mms-alfresco#325]
I have imported mms project as a  maven project from git hub and followed the instructions given in its README file to run and test Alfresco. While testing the application I have entered http://localhost:8080/share/ for which I am successfully getting the login page for Alfresco. But when I am giving the default username and password (i.e. admin and admin) I am not able to login to the application. Getting an error "Your authentication details have not been recognized or Alfresco may not be available at this time." When I checked the console and the Alfresco log file, I found org.springframework.beans.factory.BeanCreationException followed by org.alfresco.error.AlfrescoRuntimeException: 09050000 GetModelsDiff return status is 404.

Installed the following:

Apache Tomcat 7.0 version

PostgreSQL 9.4

Also installed the dependencies needed for the project(Elastic Search6.4 and ActiveMQ5.0).

Working on Java8.

Can anyone please help me out in solving the problem?

Thanks in advance.

**Comment by borromeotlhs** [comment]
log file?

**Comment by SripriyaAkondi** [comment]
Hi below is the Alfresco log file and also I am attaching the exceptions that I found on my eclipse console while running the application.
Alfresco Log file:
[Alfresco.log](https://github.com/Open-MBEE/mms/files/2469404/Alfresco.log)

Exceptions observed in my console:
[console.log](https://github.com/Open-MBEE/mms/files/2469405/console.log)

Thanks

**Comment by HuiJun** [comment]
Looks like the log says you're missing mms.properties in the mms-ent directory. Simply copy mms.properties.example to mms.properties. The default values should be enough to run locally. BTW, Elasticsearch should be version 5.6, since we do not support or test on 6.4
