### ISSUE TITLE
Importing MDK project 

### ISSUE THREAD

**Issue by SripriyaAkondi** [Open-MBEE/mms-alfresco#328]
Hi,
  I am having trouble while setting up the workspace for mdk project. I have imported the project as a java project but I can observe a lot of errors in my workspace. So can you let me know how should I  import the project (i.e. as a java project or maven project) as there is no README.md file given for the mdk project. 
I couldn't find where can I post my question regarding mdk project as there is no Issues tab for MDK project.
So can you please help me out in resolving the problem?

Also, I have one query regarding the MMS project.  How are  MMS and Alfresco related to each other?
Because if I log in to the Alfresco with username and password as "admin" and "admin" I cannot find any details regarding the MMS project? Where can I find the details of MMS project after login to Alfresco?

Thanks

**Comment by HuiJun** [comment]
Hi Sripriya, issues for MDK should be directed here: https://openmbee.atlassian.net/projects/MDK/issues.  Alfresco and MMS are linked as MMS Organizations -> Alfresco site. Projects will be located in a subdirectory under the site folder to allow alfresco to manage permission inheritance.
