### ISSUE TITLE
POST of element after DELETE results in 304 'Is Equivalent' warning

### ISSUE THREAD

**Issue by zwelz3** [Open-MBEE/mms-alfresco#332]
Hello, I'm working on an MMS client for scraping and posting elements from an external tool. During the testing process, I am trying to clean up elements that are no longer needed, and reuse their IDs for future POST requests. I've found that a deleted element seems to persist somewhere that prevents the server from allowing it to be POSTed. I've tried to create a straightforward reproduction in the code below:

```python
import requests

username = ""
password = ""
project_id = ""
branch = "master"

base_url = r"https://mms.openmbee.org/alfresco/service"
elements_url = f"{base_url}/projects/{project_id}/refs/{branch}/elements"

session = requests.Session()
session.auth = (username, password)

payload = {
    "elements": [
        {
            "id": "MMS_some_fake_id_123",
            "name": "test element",
        }
    ],
}

response = session.post(elements_url, json=payload)
```
> <Response [200]>

`response = session.post(elements_url, json=payload)`
> <Response [200]>

`response = session.get(elements_url+f"/{response.json()['elements'][0]['id']}")`
> <Response [410]>  # deleted

```
response = session.post(elements_url, json=payload)
# returns <Response [200]>
response.json()
```
>{
 '_creator': 'NAME',
 'elements': [],
 'rejected': [{'code': 304.0,
   'element': {'name': 'test element',
    'id': 'MMS_some_fake_id_123',
    '_projectId': 'PROJECT_ID',
    '_refId': 'master',
    '_inRefIds': ['master'],
    'ownerId': 'holding_bin_PROJECT_ID'},
   'message': 'Is Equivalent',
   'severity': 'warn'}]}

`response = session.get(elements_url+f"/{response.json()['elements'][0]['id']}")`
> <Response [410]>  # deleted

Is there an appropriate way to get the server to accept the POST, a way to clean up deleted elements, or is this by design? I have managed to create a workaround by modifying the POST payload 'name' so that it tricks the server into thinking the element has been modified, but a cleaner approach would be preferable. 

Thanks,
Zach

**Comment by HuiJun** [comment]
Hi Zach,

This is a known bug. The current workaround is to change an attribute in the JSON that is being posted. We'll have a fix in the next patch. Thanks.

Jason

**Comment by zwelz3** [comment]
Thanks @HuiJun. Glad to hear it's been identified and a fix is on the way.
